import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Spells</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full flex-grow bg-orange-100">
        <div className="container mx-auto px-4 py-8">
          <h1 className="text-center text-3xl font-semibold">Spells Page</h1>
        </div>
      </main>
    </>
  )
}
